apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: rdrio2/devopsbtsai:latest
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: streamlit-files
              mountPath: /app/files
      volumes:
        - name: streamlit-files
          configMap:
            name: streamlit-files
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30081
