services:
  api_blue:
    build: ./api
    container_name: api_blue
    environment:
      - APP_ENV=staging
    networks: [gateway-net]

  api_green:
    build: ./api
    container_name: api_green
    environment:
      - APP_ENV=prod
    networks: [gateway-net]

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/active-upstream.conf:/etc/nginx/conf.d/active-upstream.conf:ro
    depends_on:
      - api_blue
      - api_green
    networks: [gateway-net]

networks:
  gateway-net:
    driver: bridge
